# Julia Pieza Learning Diary {.unnumbered}

Hello, I’m Julia and this is my CASA0025 Remote Sensing Learning Diary. I’m currently completing the MSc in Urban Spatial Science at UCL whilst also working as a Senior Research and Intelligence officer at Brent Council.

After graduating with a History & Politics degree I began working at Brent first completing the NGDP Graduate Scheme and then joining the Data & Insight team. 

My journey with GIS started at Brent where as an analyst I got the opportunity to learn how to work with geospatial data. Since then I've enjoyed the ability to work data analysis projects that help frontline services operate and make a difference to the lives of local residents. 

At the moment I’m exploring the uses satellite data has in local government, for example addressing challenges like climate change the risks that more extreme weather events pose to urban settings. 

I'm looking forward to sharing my learning throughout this module and being able to share my thoughts on new ways of utilising remotely sensed data to make a difference on a local level.
